# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f50beb8e89c25402c8ad41c2aa2afb7bf9a4374e7968684f33c675ff7ba60ef5715a20a2df6b5bdac185e81af7c3709ce34149cdc009a312f092fa5c60b6984f

test:
  secret_key_base: 94e91eb8f59939d917a325840bd6e06dcd834e7ef1cd0f154a94f339b3448a5ebf226fbbf51b9ad21335c1e336d29abfd436605ecdb3fdf21cea80d0a30c1674

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
